permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Alex Jing
  email: alexjing2014@gmail.com
  link: http://www.jinghaifeng.com
  weibo: http://weibo.com/v1000001000
  github: https://github.com/JingHaifeng
#  music: http://site.douban.com/linanya
#  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 景海峰的博客
description: Accompanied by shadow
url: http://www.jinghaifeng.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# 待配置
# google analytics 设置
#ga:
#  id: UA-54262064-1 
#  url: painterlin.com

# disqus 设置
disqus:
  shortname: alex

# 主题设置，自动激活某个标签
active: 读书

# 待设置
# 首页除了最新文章外显示分类
#cates: 
#  - Optimization
#  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
